# ------------------------------------------------------------------------------
# Kafka:
# ------------------------------------------------------------------------------

Replicas: 3
Image: "solsson/kafka"
ImageTag: "0.11.0.0"
ImagePullPolicy: "IfNotPresent"
resources: 
  requests:
    cpu: 250m
    memory: 512Mi 
  limits:
    cpu: 250m 
    memory: 512Mi 
  # limits:
  #   cpu: 200m
  #   memory: 1536Mi
  # requests:
  #   cpu: 100m
  #   memory: 1024Mi
heap: "1G"
Storage: "1Gi"
# StorageClass: default
DataDirectory: "/opt/kafka/data"

# ------------------------------------------------------------------------------
# Zookeeper:
# ------------------------------------------------------------------------------

zookeeper:
  Enabled: false
  Servers: 3
  Resources: {}
  Heap: "256M"
  Storage: "1Gi"
  # StorageClass: default
  ServerPort: 2888
  LeaderElectionPort: 3888
  ClientPort: 2181
  ImagePullPolicy: "IfNotPresent"
  TickTimeMs: 2000
  InitTicks: 10
  SyncTicks: 5
  ClientCnxns: 60
  SnapRetain: 3
  PurgeHours: 1
  ProbeInitialDelaySeconds: 15
  ProbeTimeoutSeconds: 5
  AntiAffinity: "hard"
  LogLevel: "INFO"
  # If the Zookeeper Chart is disabled a URL and port are required to connect
  Url: "zkkafka-zookeeper"
  Port: 2181
